---
output:
  bookdown::pdf_document2:
    keep_tex: true
    toc: false
  bookdown::word_document2:
    toc: false
geometry: margin=1.0in
font-size: 14pt
header-includes:
  - \usepackage{helvet}
  - \renewcommand*\familydefault{\sfdefault}
bibliography: references.bib
csl: https://www.zotero.org/styles/estuarine-coastal-and-shelf-science
---

```{r params, echo = FALSE, include = FALSE, message = FALSE}

tar_load(journal_name)

```

Dear Prof. Daniel Baird,

Herewith I am resubmitting an article titled “Fin-spine microchemistry discriminates regional stocks of 
Caspian Sea starry sturgeon” for consideration for publication in *`r journal_name`*. It was recommended that we resubmit our manuscrpt
following major revisions.

Attached is our extensively revised manuscript and a detailed point-by-point response to the reviewers' comments, questions, and suggestions.
Based on the helpful input from the reviewers, we have re-done some of our analyses using nonparametric tests, which did not greatly alter our conclusions but did improve 
the statistical rigor of our work. We also outlined our hypothesis and motivation more clearly, made limitations of our methodology more transparent (and outlined the
steps we took to account for this), and rewrote most of the Discussion section to better contextualize our results in terms of both the 
microchemistry literature and the environmental conditions of the Caspian Sea. We did not include any new figures or tables, but updated some of them following 
reviewer comments. Table 1 now includes more granular summary data (subdivided by sampling area instead of just region). 
The results shown in Figure 2 and Table 2 were updated due to our switch from parametric to nonparamteric tests.
Finally, we added a second panel to Figure 3 to improve interpretation of our PCA results.

We feel that our article has been greatly improved by this review and
hope that it now meets the standards of *`r journal_name`* and the reviewers.

On behalf of my co-authors, I thank you and the reviewers for the time, effort, and care given to our manuscript.
I wish you all the best and look forward to hearing back.

Sincerely,

Theodore Hermann